import {z} from "zod";

export const CreatePostInformationSchema = z.object({
    category: z.string().nullable(),
    version_id: z.int().default(1).optional(),
    post_id: z.string(),
    post_title: z.string().nullable(),
    publish_time: z.string().nullish(),
    duration: z.number().int(),
    engaged_views: z.number().int().nullish(),
    average_view_duration: z.string().nullish(),
    average_viewed_percent: z.number().nullish(),
    stayed_to_watch_percent: z.number().nullish(),
    unique_viewers: z.int().nullish(),
    unique_reach: z.int().nullish(),
    average_views_per_viewer: z.number().nullish(),
    new_viewers: z.int().nullish(),
    returning_viewers: z.int().nullish(),
    casual_viewers: z.int().nullish(),
    regular_viewers: z.int().nullish(),
    hypes: z.int().nullish(),
    hype_points: z.int().nullish(),
    subscribers_gained: z.int().nullish(),
    subscribers_lost: z.int().nullish(),
    likes: z.int().nullish(),
    dislikes: z.int().nullish(),
    likes_vs_dislikes_percent: z.number().nullish(),
    shares: z.int().nullish(),
    comments_added: z.int().nullish(),
    total_sales_usd: z.number().nullish(),
    orders: z.int().nullish(),
    approved_commissions_usd: z.number().nullish(),
    pending_commissions_usd: z.number().nullish(),
    removed_commission_usd: z.number().nullish(),
    youtube_premium_views: z.number().int().nullish(),
    youtube_premium_watch_time_hours: z.number().nullish(),
    playlist_watch_time_hours: z.number().nullish(),
    views_from_playlist: z.int().nullish(),
    views_per_playlist_start: z.number().nullish(),
    hours_streamed: z.number().nullish(),
    reminders_set: z.int().nullish(),
    chat_messages: z.int().nullish(),
    reactions: z.int().nullish(),
    remix_count: z.int().nullish(),
    remix_views: z.int().nullish(),
    community_clip_views: z.int().nullish(),
    watch_time_from_community_clips_hours: z.number().nullish(),
    card_clicks: z.int().nullish(),
    cards_shown: z.int().nullish(),
    clicks_per_card_shown_percent: z.number().nullish(),
});

export const PostInformationSchema = z.object({
    id: z.uuid(),
    import_date: z.date(),
    ...CreatePostInformationSchema.shape
});

export type CreatePostInformationDto = z.infer<typeof CreatePostInformationSchema>;
export type PostInformationDto = z.infer<typeof PostInformationSchema>;