import { z } from "zod";

export const CreatePostInformationSchema = z.object({
  category: z.string().optional(),
  version_id: z.int().default(1).optional(),
  post_id: z.string(),
  post_title: z.string(),
  publish_time: z.iso.datetime({ offset: true }),
  duration: z.number().int(),
  engaged_views: z.number().int(),
  average_view_duration: z.string(),
  average_percentage_viewed_percent: z.number(),
  stayed_to_watch_percent: z.number(),
  unique_viewers: z.number().int(),
  unique_reach: z.number().int(),
  average_views_per_viewer: z.number(),
  new_viewers: z.number().int(),
  returning_viewers: z.number().int(),
  casual_viewers: z.number().int(),
  regular_viewers: z.number().int(),
  hypes: z.number().int(),
  hype_points: z.number().int(),
  subscribers_gained: z.number().int(),
  subscribers_lost: z.number().int(),
  likes: z.number().int(),
  dislikes: z.number().int(),
  likes_vs_dislikes_percent: z.number(),
  shares: z.number().int(),
  comments_added: z.number().int(),
  total_sales_usd: z.number(),
  orders: z.number().int(),
  approved_commissions_usd: z.number(),
  pending_commissions_usd: z.number(),
  removed_commission_usd: z.number(),
  youtube_premium_views: z.number().int(),
  youtube_premium_watch_time_hours: z.number(),
  playlist_watch_time_hours: z.number(),
  views_from_playlist: z.number().int(),
  views_per_playlist_start: z.number(),
  hours_streamed: z.number(),
  reminders_set: z.number().int(),
  chat_messages: z.number().int(),
  reactions: z.number().int(),
  remix_count: z.number().int(),
  remix_views: z.number().int(),
  community_clip_views: z.number().int(),
  watch_time_from_community_clips_hours: z.number(),
  card_clicks: z.number().int(),
  cards_shown: z.number().int(),
  clicks_per_card_shown_percent: z.number(),
});

export const PostInformationSchema = z.object({
  id: z.uuid(),
  version_id: z.number().int(),
  import_date: z.iso.datetime({ offset: true }),
  category: z.string(),
  post_id: z.string(),
  post_title: z.string(),
  publish_time: z.iso.datetime({ offset: true }),
  duration: z.number().int(),
  engaged_views: z.number().int(),
  average_view_duration: z.string(),
  average_percentage_viewed_percent: z.number(),
  stayed_to_watch_percent: z.number(),
  unique_viewers: z.number().int(),
  unique_reach: z.number().int(),
  average_views_per_viewer: z.number(),
  new_viewers: z.number().int(),
  returning_viewers: z.number().int(),
  casual_viewers: z.number().int(),
  regular_viewers: z.number().int(),
  hypes: z.number().int(),
  hype_points: z.number().int(),
  subscribers_gained: z.number().int(),
  subscribers_lost: z.number().int(),
  likes: z.number().int(),
  dislikes: z.number().int(),
  likes_vs_dislikes_percent: z.number(),
  shares: z.number().int(),
  comments_added: z.number().int(),
  total_sales_usd: z.number(),
  orders: z.number().int(),
  approved_commissions_usd: z.number(),
  pending_commissions_usd: z.number(),
  removed_commission_usd: z.number(),
  youtube_premium_views: z.number().int(),
  youtube_premium_watch_time_hours: z.number(),
  playlist_watch_time_hours: z.number(),
  views_from_playlist: z.number().int(),
  views_per_playlist_start: z.number(),
  hours_streamed: z.number(),
  reminders_set: z.number().int(),
  chat_messages: z.number().int(),
  reactions: z.number().int(),
  remix_count: z.number().int(),
  remix_views: z.number().int(),
  community_clip_views: z.number().int(),
  watch_time_from_community_clips_hours: z.number(),
  card_clicks: z.number().int(),
  cards_shown: z.number().int(),
  clicks_per_card_shown_percent: z.number(),
});

export type CreatePostInformationDto = z.infer<typeof CreatePostInformationSchema>;
export type PostInformationDto = z.infer<typeof PostInformationSchema>;