import {z} from "zod";

export const CreatePostInformationSchema = z.object({
    category: z.string().optional(),
    version_id: z.int().default(1).optional(),
    post_id: z.string(),
    post_title: z.string().optional(),
    publish_time: z.string().optional(),
    duration: z.number().int(),
    engaged_views: z.number().int().optional(),
    average_view_duration: z.string().optional(),
    average_viewed_percent: z.number().optional(),
    stayed_to_watch_percent: z.number().optional(),
    unique_viewers: z.number().int().optional(),
    unique_reach: z.number().int().optional(),
    average_views_per_viewer: z.number().optional(),
    new_viewers: z.number().int().optional(),
    returning_viewers: z.number().int().optional(),
    casual_viewers: z.number().int().optional(),
    regular_viewers: z.number().int().optional(),
    hypes: z.number().int().optional(),
    hype_points: z.number().int().optional(),
    subscribers_gained: z.number().int().optional(),
    subscribers_lost: z.number().int().optional(),
    likes: z.number().int().optional(),
    dislikes: z.number().int().optional(),
    likes_vs_dislikes_percent: z.number().optional(),
    shares: z.number().int().optional(),
    comments_added: z.number().int().optional(),
    total_sales_usd: z.number().optional(),
    orders: z.number().int().optional(),
    approved_commissions_usd: z.number().optional(),
    pending_commissions_usd: z.number().optional(),
    removed_commission_usd: z.number().optional(),
    youtube_premium_views: z.number().int().optional(),
    youtube_premium_watch_time_hours: z.number().optional(),
    playlist_watch_time_hours: z.number().optional(),
    views_from_playlist: z.number().int().optional(),
    views_per_playlist_start: z.number().optional(),
    hours_streamed: z.number().optional(),
    reminders_set: z.number().int().optional(),
    chat_messages: z.number().int().optional(),
    reactions: z.number().int().optional(),
    remix_count: z.number().int().optional(),
    remix_views: z.number().int().optional(),
    community_clip_views: z.number().int().optional(),
    watch_time_from_community_clips_hours: z.number().optional(),
    card_clicks: z.number().int().optional(),
    cards_shown: z.number().int().optional(),
    clicks_per_card_shown_percent: z.number().optional(),
});

export const PostInformationSchema = z.object({
    id: z.uuid(),
    version_id: z.number().int(),
    import_date: z.date(),
    category: z.string().nullable().optional(),
    post_id: z.string(),
    post_title: z.string().optional(),
    publish_time: z.string().nullable(),
    duration: z.number().int(),
    engaged_views: z.number().int().optional(),
    average_view_duration: z.string().optional(),
    average_viewed_percent: z.number().optional(),
    stayed_to_watch_percent: z.number().optional(),
    unique_viewers: z.number().int().optional(),
    unique_reach: z.number().int().optional(),
    average_views_per_viewer: z.number().optional(),
    new_viewers: z.number().int().optional(),
    returning_viewers: z.number().int().optional(),
    casual_viewers: z.number().int().optional(),
    regular_viewers: z.number().int().optional(),
    hypes: z.number().int().optional(),
    hype_points: z.number().int().optional(),
    subscribers_gained: z.number().int().optional(),
    subscribers_lost: z.number().int().optional(),
    likes: z.number().int().optional(),
    dislikes: z.number().int().optional(),
    likes_vs_dislikes_percent: z.number().optional(),
    shares: z.number().int().optional(),
    comments_added: z.number().int().optional(),
    total_sales_usd: z.number().optional(),
    orders: z.number().int().optional(),
    approved_commissions_usd: z.number().optional(),
    pending_commissions_usd: z.number().optional(),
    removed_commission_usd: z.number().optional(),
    youtube_premium_views: z.number().int().optional(),
    youtube_premium_watch_time_hours: z.number().optional(),
    playlist_watch_time_hours: z.number().optional(),
    views_from_playlist: z.number().int().optional(),
    views_per_playlist_start: z.number().optional(),
    hours_streamed: z.number().optional(),
    reminders_set: z.number().int().optional(),
    chat_messages: z.number().int().optional(),
    reactions: z.number().int().optional(),
    remix_count: z.number().int().optional(),
    remix_views: z.number().int().optional(),
    community_clip_views: z.number().int().optional(),
    watch_time_from_community_clips_hours: z.number().optional(),
    card_clicks: z.number().int().optional(),
    cards_shown: z.number().int().optional(),
    clicks_per_card_shown_percent: z.number().optional()
});

export type CreatePostInformationDto = z.infer<typeof CreatePostInformationSchema>;
export type PostInformationDto = z.infer<typeof PostInformationSchema>;